FROM dockerymh/hmtpbsa:gmx_openmpi_patch

RUN pip install sh tqdm && \
    pip install --upgrade "dp-launching-sdk" -ihttps://repo.mlops.dp.tech/repository/pypi-group/simple

RUN source activate amber21 && \
    pip install sh && \
    pip install --upgrade "dp-launching-sdk" -ihttps://repo.mlops.dp.tech/repository/pypi-group/simple

ARG version=0.1.6
COPY dist/unigbsa-$version.tar.gz /data/
RUN source activate amber21             && \
    cd /data/                           && \
    tar zxvf unigbsa-$version.tar.gz    && \ 
    cd unigbsa-$version                 && \
    python setup.py install             && \
    mkdir /app/                         && \
    cp launching /app/ -r               && \
    rm -rf /data/*


RUN echo `which python`


# Uni-protprep
COPY dist/unisp-0.0.0-py3-none-any.whl /data
RUN conda create -n protprep -c https://conda.mlops.dp.tech:443/biosim openmm networkx propka libpng libtiff msys_viparr ost_promod gemmi -c conda-forge -c anaconda \
&& source activate protprep \
&& conda remove --force cudatoolkit \
&& cd /data/                \
&& pip install unisp-0.0.0-py3-none-any.whl \
&& wget -O propka-3.5.1+0.ge5b0b8f.dirty-py3-none-any.whl https://openfiles.mlops.dp.tech/projects/uni-protein-sp/2d86a6da39624709a0d76e586ffc8c91/propka-3.5.1+0.ge5b0b8f.dirty-py3-none-any.whl \
&& echo "d4bb2120cc5c594c19a2fb3232c32a3d  propka-3.5.1+0.ge5b0b8f.dirty-py3-none-any.whl" | md5sum -c \
&& pip install propka-3.5.1+0.ge5b0b8f.dirty-py3-none-any.whl \
&& rm -rf ~/.cache/* \
&& rm -rf /data/* \
&& rm -rf /opt/conda/pkgs/*



# COPY sources.list /etc/apt/sources.list
RUN  sed -i s@/archive.ubuntu.com/@/mirrors.aliyun.com/@g /etc/apt/sources.list
RUN apt update -y
RUN apt install -y vim sudo

# RUN apt-get update \
# && apt-get install -y sudo

RUN groupadd -g 1000 webshell
RUN adduser --disabled-password --gecos '' --uid 1000 --gid 1000 webshell
RUN adduser webshell sudo
RUN echo '%sudo ALL=(ALL) NOPASSWD:ALL' >> /etc/sudoers
